#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for storage/doublewrite
#
# IDENTIFICATION
#    src/backend/storage/doublewrite/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/storage/doublewrite
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	doublewrite.o

include $(top_srcdir)/src/backend/common.mk
