#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for storage/map (Umbra mapping subsystem)
#
# IDENTIFICATION
#    src/backend/storage/map/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/storage/map
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	map.o \
	mapinit.o \
	mapbuf.o \
	mapbgproc.o \
	mapflush.o \
	mapclock.o \
	mapinflight.o \
	mapsuper.o

include $(top_srcdir)/src/backend/common.mk
